export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';
// Login
export const REQUEST_ACCESS = 'REQUEST_ACCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
// Algolia
export const SETUP_ALGOLIA_CLIENT = 'SETUP_ALGOLIA_CLIENT';
// Layer Client
export const CREATE_USER_CLIENT = 'CREATE_USER_CLIENT';
export const CLIENT_READY = 'CLIENT_READY';
export const CLIENT_RESET = 'CLIENT_RESET';
export const REQUEST_CONVERSATION_JOIN = 'REQUEST_CONVERSATION_JOIN';
export const RECEIVE_CONVERSATION_JOIN = 'RECEIVE_CONVERSATION_JOIN';
export const RESET_CONVERSATION_JOIN = 'RESET_CONVERSATION_JOIN';
// App
export const REQUEST_USER_INFO = 'REQUEST_USER_INFO';
export const RECEIVE_USER_INFO = 'RECEIVE_USER_INFO';
export const LOGOUT = 'LOGOUT';

// Event Fetch actions
export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const QUERY_EVENTS = 'QUERY_EVENTS';
export const LOAD_MORE_EVENTS = 'LOAD_MORE_EVENTS';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
// Timeout actions
export const SET_EVENTS_TIMEOUT = 'SET_EVENTS_TIMEOUT';
export const CLEAR_EVENTS_TIMEOUT = 'CLEAR_EVENTS_TIMEOUT';
// Search
export const SEARCH_CHANGE = 'SEARCH_CHANGE';
// Pages
export const REQUEST_PAGE = 'REQUEST_PAGE';
export const RECEIVE_PAGE = 'RECEIVE_PAGE';
// Sites
export const REQUEST_SITE = 'REQUEST_SITE';
export const RECEIVE_SITE = 'RECEIVE_SITE';
// Users
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const NOT_FOUND_USER = 'NOT_FOUND_USER';
// Users
export const REQUEST_LAYER_USER = 'REQUEST_LAYER_USER';
export const RECEIVE_LAYER_USER = 'RECEIVE_LAYER_USER';
export const NOT_FOUND_LAYER_USER = 'NOT_FOUND_LAYER_USER';
// Conversation
export const REQUEST_PARTICIPANTS = 'REQUEST_PARTICIPANTS';
export const RECEIVE_PARTICIPANTS = 'RECEIVE_PARTICIPANTS';
export const REQUEST_CONVERSATION = 'REQUEST_CONVERSATION';
export const SET_CONVERSATION = 'SET_CONVERSATION';
export const RECEIVE_CONVERSATION = 'RECEIVE_CONVERSATION';
export const CHANGE_COMPOSER_MESSAGE = 'CHANGE_COMPOSER_MESSAGE';
export const SUBMIT_COMPOSER_MESSAGE = 'SUBMIT_COMPOSER_MESSAGE';
export const SEND_COMPOSER_MESSAGE = 'SEND_COMPOSER_MESSAGE';
export const RECEIVE_COMPOSER_MESSAGE = 'RECEIVE_COMPOSER_MESSAGE';

export const REQUEST_CONVERSATIONS_USERS = 'REQUEST_CONVERSATIONS_USERS';
export const RECEIVE_CONVERSATIONS_USERS = 'RECEIVE_CONVERSATIONS_USERS';
